server:
  port: 12000
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: gulimall-seckill
  redis:
    host: 192.168.50.10
    port: 6379
    password: redis
  # 定时任务异步执行线程池配置
  task:
    execution:
      pool:
        core-size: 4
        max-size: 10
  # 设置sprinboot返回json格式数据时对于Date类的处理方式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
    host: 192.168.50.10
    virtual-host: /
    port: 5672
    # 生产端确认回调
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  thymeleaf:
    cache: false
