server:
  port: 11000

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.10:3306/gulimall_wms?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: gulimall-ware
  #    nacos注册中心地址配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.50.10
    port: 5672
    virtual-host: /
    # 手动ack
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
#   分配ID(主键类型为Number(Long和Integer)或String)(since 3.3.0),
#  使用接口IdentifierGenerator的方法nextId
#  (默认实现类为DefaultIdentifierGenerator雪花算法)
      id-type: auto

logging:
  level:
    com.vivi.gulimall.ware: debug